name := "Simple Project"
version := "1.0"
scalaVersion := "2.12.15"
libraryDependencies += "org.apache.kafka" % "kafka-clients" %  "2.8.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.2.1" 
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "3.2.1" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-streaming-kafka-0-10" % "3.2.1" % "provided"
